import useSWR from 'swr';

const FMA_cassettes = [
	{ ID: "FMAC02", "Digitised": "Y", "Digitised by": "Philip Snow (A only?)", "Type": "", "Artist": "Sumosonic", "Item Name": "Audio Aquatic Sound System", "Date": "1996", "Side A Track List": "Come, Friendly Spaceman/Nobody On God's Green Earth/Fern Schnell Gut/Destroy All Monsters/Cat's Life/Business And Work/We Are The Traffic/Everything Is Wonderful/Radio Saigon/Sputnik/Hey Stupid!/My Ultimate Baby/ (The Hypnotic Eye) ", "Side B Track List": "", "Scanned?": "", "Notes": "Includes She Moved Through The Fair and The Hypnotic Eye. Never released" },
	{ ID: "FMAC03", "Digitised": "Y", "Digitised by": "Philip Snow", "Type": "", "Artist": "Pat Fish", "Item Name": "My Guitar will only tune to G", "Date": "?", "Side A Track List": "Bad Blues / Mad Blues / Space Blues", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC04", "Digitised": "Y", "Digitised by": "Philip Snow", "Type": "", "Artist": "Alan Moore", "Item Name": "Alan Moore Rough Mixes", "Date": "?", "Side A Track List": "Tokyo (drums gaspacho mix) / Tokyo (small drums big fish) / London (the long mix) / London (short won) / Blake / Blake Spacious MIxing", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC05", "Digitised": "Y", "Digitised by": "Philip Snow", "Type": "", "Artist": "", "Item Name": "Borderline", "Date": "?", "Side A Track List": "", "Side B Track List": "", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC06", "Digitised": "Y", "Digitised by": "Philip Snow", "Type": "", "Artist": "", "Item Name": "Doctor Anthrax", "Date": "?", "Side A Track List": "Doctor Anthrax Inst. (w/Bass) / Doctor Anthrax Inst. (no bass)", "Side B Track List": "", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC07", "Digitised": "Y", "Digitised by": "Philip Snow", "Type": "", "Artist": "", "Item Name": "Drac-U-Like", "Date": "?", "Side A Track List": "WHO IS IT? (It's Dracula)", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC08", "Digitised": "Y", "Digitised by": "Jimmy Duval", "Type": "Studio", "Artist": "JBC", "Item Name": "Bugbrooke Ace Sessions 1986", "Date": "1986", "Side A Track List": "Conspiracy (Rough Mix), Conspiracy (E.P. Mix), Peter Lorre, Big Old Wind, It Has To Be You", "Side B Track List": "Conspiracy (Vocal Mix #1), Olof Palme, Falling In Love, Angels (Mix 1), Angels (Mix 2) ", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC09", "Digitised": "Y", "Digitised by": "Jimmy Duval", "Type": "", "Artist": "Various", "Item Name": "Weirdos From Northampton Spittle Rattle Alan Moore JBC", "Date": "1992/1993/2001?", "Side A Track List": "Spittle Rattle-I Will Take You There 1+2, Gushy Shite", "Side B Track List": "JBC Trouble Every Day #1, Trouble Every Day (With Curt), Alan Moore-London, London (Big Mix), Trampling Tokyo, London (Blake Mix), Litvinoff's Book 2-14-2001,  JB Demo-Blue Cirle Waters", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC10", "Digitised": "Y", "Digitised by": "?", "Type": "", "Artist": "JBC", "Item Name": "Love Bus outtakes", "Date": "1994", "Side A Track List": "I Never Know When To Say When, (*next 3 tracks were low quality and not transferred since we have higher quality versions)*Vodka Girls, Truck Of Fear, Sebastian's Medication", "Side B Track List": "Blank", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC11", "Digitised": "Y", "Digitised by": "Nick Bourne", "Type": "Studio", "Artist": "JBC", "Item Name": "JBC Livingston Studios 1986 / Drum Patterns", "Date": "1986-01-08", "Side A Track List": "The Jazz Butcher-Partytime, Hard (12\" Mix), Hard (7\" Mix), We Are The Elephant Men, Grooving In The Buslane, The Partys Over (Version 1), The Partys Over (Version 2)  ", "Side B Track List": "Drum Patterns-Rockabilly/Jungle 000, Funk 040, \"Spencer Davis' Soul\" 085, Latin Effort 122, Fast Rock N' Roll 167, Slow Ballad 167,  Mid-Pace Pop Thing 269, Slow 6/8 Ballad 311", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC12", "Digitised": "Y", "Digitised by": "?", "Type": "Backing Tracks", "Artist": "JBC", "Item Name": "Backing Tracks In Stereo (88-94)", "Date": "1988-1994", "Side A Track List": "Argentine Basement Blues, When Eno Sings, Jean Coutts Girlfriend (Shakey), Monkeyface, Scarlett, Old Snakey, De Basement, Basment Psychedelico, Panic In Room 109, Pineapple Tuesday In Dub", "Side B Track List": "Basement Original XII, Shirley Maclaine, Racheland, Nico In The Mailcoach, Sister Death, She's on Drugs, 16 Years, Cops & Hospital, Bubonic Plague, Argentine Basement Of Despair, Concrete Spongiform Basement", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC13", "Digitised": "Y", "Digitised by": "?", "Type": "Backing Tracks", "Artist": "JBC", "Item Name": "JBC Instrumental Mixes", "Date": "1994", "Side A Track List": "Yokohama / The Land Before Time / Blue Circle E drone / The Egyptian Bar / When Eno Sings / Oh Jean (Hey Scarlett)", "Side B Track List": "Old Snakey (rrruff!) / Old Snakey (Vocal) / Nico in the Mailcoach / O- Blue Circle Edrone 2 - I hate you - Our Manc Friend", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC14", "Digitised": "Y", "Digitised by": "?", "Type": "Mixed", "Artist": "JBC", "Item Name": "The Jazz Butcher Boils His Head Butch solo", "Date": "August 1985", "Side A Track List": "Forever, Vienna Song, Lost In France 1, Lost In France 2, Thing, Bus Lane, The Hairbrush & The Tank, Elephant Man, Sheep", "Side B Track List": "", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC15", "Digitised": "Y", "Digitised by": "?", "Type": "Demo", "Artist": "JBC", "Item Name": "Condition Blue Mixes - Fag Rock", "Date": "1991", "Side A Track List": "When Girls Say Yes, John Coutts Dreamgirl instru., Honey Wants, Time Enough At Last, Railway Bridge, [Ansaphone Fun]", "Side B Track List": "Shirley Maclaine, Rachel Land, Harlan, Dinosaur City", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC16", "Digitised": "Y", "Digitised by": "?", "Type": "", "Artist": "", "Item Name": "SHAKE!", "Date": "?", "Side A Track List": "Love Penitentiary, Shake 7\" A, Shake 7\" B, Shake 7\" C, Shake 12\"", "Side B Track List": "", "Scanned?": "Yes", "Notes": "With Pat Fish, Joe Foster, John Dean, Angus Wallace, Alan Holloway" },
	{ ID: "FMAC17", "Digitised": "Y", "Digitised by": "?", "Type": "Demo", "Artist": "JBC", "Item Name": "The Jazz Butcher #3", "Date": "1982", "Side A Track List": "Mind like a playgroup / Over You / Sheep 1+2 / Lady Godiva's Operation 1 +2 / Number 42", "Side B Track List": "Poisoned by Food 1-3 / Girls who keep goldfish 1-4 / Spine", "Scanned?": "Yes", "Notes": "Looks like Demos" },
	{ ID: "FMAC18", "Digitised": "Y", "Digitised by": "?", "Type": "", "Artist": "", "Item Name": "Plastic queen Demo", "Date": "?", "Side A Track List": "Plastic Queen Demo", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC19", "Digitised": "Y", "Digitised by": "Gabriel Edvy", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher: Live in London / Clerndon July 85 / El Ballroom oct 85", "Date": "1985", "Side A Track List": "Cleaendon July 85: Real Men / Bigfoot motel / Walk with the devil / bath of bacon / my desert / I'm waiting for my man / Partytime / Pet Semetary", "Side B Track List": "Electric ballroom: Oct 85: Grooving / Big saturday / Still in the kitchen / Red Pets / The Human Jungle / Whats the matter boy / walk with the devil / Just like Betty Page / Bigfoot Motel / Grey Flannelette / Southern mark smith", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC20", "Digitised": "Y", "Digitised by": "Philip Snow", "Type": "Live", "Artist": "JBC", "Item Name": "Live Merton+Derngate (1983) / Black Lion (1982)", "Date": "1983-08-21", "Side A Track List": "Zombie Love / Love Kittens / I need meat / Chinatown / Girls who keep goldfish / Partytime / The Crusher / Southern Mark Smith / Swinging with the Pygmies / The devil is my friend", "Side B Track List": "The intro and outre / Love Kittens / My favourite things / ? Train from hell / Road Runner", "Scanned?": "Yes", "Notes": "LOts of notes, see photos" },
	{ ID: "FMAC21", "Digitised": "Y", "Digitised by": "Philip Snow", "Type": "Live", "Artist": "JBC", "Item Name": "Music is for everyone man - Live Kingston Poly (1983)", "Date": "November 1983", "Side A Track List": "The Jazz Butcher and Max at Kingston Poly November 1983 / The wooden tops", "Side B Track List": "", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC22", "Digitised": "Y", "Digitised by": "Steve", "Type": "Live+Interview", "Artist": "JBC", "Item Name": "JBC Nantes + Interview", "Date": "1986-02-27", "Side A Track List": "JBVCD / Big Saturday / Groovin' / Soul Happy hour / hard / still in the kitchen / human jungle / wha's the matter boy / ", "Side B Track List": "Walk with the devil / partytime / death dentist / marnie / road runner / *? / southern mark smith / mind like a playgroup", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC23", "Digitised": "Y", "Digitised by": "Steve", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Rennes ", "Date": "1988-03-10", "Side A Track List": "GRey Flanelette  / real men / soul happy hour / caroline / the best way / the best way / girlfriend / southern mark smith / susie / lot 49", "Side B Track List": "out of touch / sex engine thing / spooky / conspiracy / jbvcd / skinheads/ la mer / zombie love", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC24", "Digitised": "Y", "Digitised by": "Steve", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher and Alex Green live in logo club hamburg", "Date": "1987-01-26", "Side A Track List": "angels / southern mark smith / envoy / girlfriend / hungarian food sex / sex engine / betty ", "Side B Track List": "groovin / zombie love / speedy gonzalez / soul / cowgirl / partytime / rain / olof / see emily play", "Scanned?": "Yes", "Notes": "Part one of two" },
	{ ID: "FMAC25", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "Live", "Artist": "JBC", "Item Name": "Pat Fish and Alex Green – Poitiers", "Date": "1987-02-07", "Side A Track List": "Southern mark smith / ? / hungarian love song / partytime / ? / girlfriend / leaving it up to you / envoy / zombielove / domestic animal / buslane", "Side B Track List": "angels / sex engine / betty page / speedy / swell / road runner / sweet jane / ? / the devil is m friend / stand by me", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC26", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher - Bop Bar Evreux", "Date": "1987-02-12", "Side A Track List": "?", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "Unlabled " },
	{ ID: "FMAC27", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher - Maxwells Hoboken", "Date": "1986-07-16", "Side A Track List": "Big saturday / groovin / jungle / kitchen / girlfriend / whats the matter boy / water / hard / hungarian love song / angels marnie ", "Side B Track List": "Partytime / southern mark smith / dentist / drink / road runner / soul happy hour / (our first ever US performance. ", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC28", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Conspiracy - New Orleans", "Date": "1992-07-15", "Side A Track List": "Partytime / Pineapple Tuesday / Girlfriend / Girl go / Susie / Falling in Love / Angels / Southern Mark Smith ", "Side B Track List": "She's a yo yo / Honey / Shirley MaClaine / Mister Odd / She's on Drugs / Racheland / Sister Death / Over the rainbow", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC29", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "", "Artist": "Sumosonic", "Item Name": "Sumo Live DEAD LOUD COPY", "Date": "August 97", "Side A Track List": "Spacemen / God's Green / Business / Wo'Ful / Saigon / Sputnik / Monks", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC30", "Digitised": "Y", "Digitised by": "?", "Type": "", "Artist": "Sumosonic", "Item Name": "Sumo Live – Master", "Date": "October 97", "Side A Track List": "Monks of Kung Fu / God's green earth / Business and Work / Sputnik / Dracula AD 2000 / Radio Saigon / Everything is Wonderful / Come Friendly Spaceman", "Side B Track List": "Master", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC31", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "", "Artist": "Sumosonic", "Item Name": "Sumo Sonic Live 98", "Date": "April 98", "Side A Track List": "Sumo Live 98", "Side B Track List": "Monks", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC32", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "Backing Tracks", "Artist": "JBC", "Item Name": "Hey Star Practice Backing Track", "Date": "?", "Side A Track List": "HEY STAR plus the rest of the live set | Hey star / Business and work / God's green earth / Monks of Kung Fu / Radio Saigon / Come Friendly Spacemen", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "On the inside of the tape list is another list for a Sumosonic live set" },
	{ ID: "FMAC33", "Digitised": "Y", "Digitised by": "Gabriel Edvy", "Type": "Interview", "Artist": "Alan Moore", "Item Name": "Alan Moore Interview Brian Eno", "Date": "? ", "Side A Track List": "Alan Moore Brian Eno Interview", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC34", "Digitised": "Y", "Digitised by": "Andy Barding", "Type": "", "Artist": "Black EG", "Item Name": "Bohemia Briteas Warphole", "Date": "?", "Side A Track List": "?", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "no notes, only one side labled" },
	{ ID: "FMAC35", "Digitised": "Y", "Digitised by": "Gabriel Edvy", "Type": "", "Artist": "Black EG", "Item Name": "Figlequarum", "Date": "1990", "Side A Track List": "Cambodia EG Mixes", "Side B Track List": "Figlequarum 1990", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC36", "Digitised": "Y", "Digitised by": "Ray Collins", "Type": "Live", "Artist": "JBC", "Item Name": "Jazz Butcher Live InStaple", "Date": "1985-09-05", "Side A Track List": "Helicopters at war (band)", "Side B Track List": "Water / Girlfriend / Soul Happy Hour / Girls who keep goldfish / Sweet Jane / Chinese envoy / Love Kittens / Zombie Love / La Mer / Partytime ", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC37", "Digitised": "Y", "Digitised by": "Ray Collins", "Type": "Live", "Artist": "JBC", "Item Name": "Jazz Butcher North East London Polytechnic", "Date": "1985-08-02", "Side A Track List": "Southern Mark Smith / Marnie / Bigfoot Motel / JBVCD / Girls who keep goldfish / Sweet Jane / Leaving it up to you / GRey Flanalette / Girlfriend / Only a rumour / Rain / Partytime / Real men / zombie love / Road runner", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC38", "Digitised": "Y", "Digitised by": "Ray Collins", "Type": "", "Artist": "Black EG", "Item Name": "The Black EG: L'Espirit Formidable Des ourvriers mondiales", "Date": "?", "Side A Track List": "Stayin' Alive / Song of the Homeland / Indianapolis 500 / Vietnam / Yokohama / Lulu' nightmare / I will survive (tribute to AYG) / Bel Air", "Side B Track List": "Sexual Taboos / CAmbodia / Je Survivral / Ciil Rights / A lovers Story / Mogadon ", "Scanned?": "Yes", "Notes": "Although it says on the cover \"for full titles and credits see accompanying paperwork = but there is no paperwork." },
	{ ID: "FMAC39", "Digitised": "Y", "Digitised by": "?", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Cotton Club Atlanta", "Date": "1989-12-12", "Side A Track List": "New Invention / Chickentown / Bicycle Kid / Burglar of love / Big Saturday / Angels / Bad Dream Lover / The Best Way / Lot 49 / Girl Go / Southern Mark Smith", "Side B Track List": "Hysteria / Carolyn Wheeler / Sex Engine / JBvPM / Mr Odd / Zombie Love / Domestic Animal / Party Time / Moscow Drug Club / The devil is my friend  / King of joy", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC40", "Digitised": "Y", "Digitised by": "Andrew Paine", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Farewell Gig London", "Date": "1995-12-12", "Side A Track List": "JBC Xmas Bye by buy", "Side B Track List": "JbC: Max's Kansas City 23 August 70", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC41", "Digitised": "Y", "Digitised by": "Dug Douglas", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Manege Munchen", "Date": "1985-11-20", "Side A Track List": "Road runner / bigfoot / saturday / whats the matter / rumour / red pets / jungle / rain / devil is my friend / marnie / Betty / groovin", "Side B Track List": "walk with the devil / kitchen / leaving it up to you / southern / girlfriend / speedy / drink / soul / the party's over", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC42", "Digitised": "Y", "Digitised by": "?", "Type": "Live", "Artist": "JBC", "Item Name": "JBC ICA London", "Date": "1984-12-30", "Side A Track List": "Girls who keep goldfish / Marnie / I Need Meat / Zombie Love / Speedy Gonzalez / Techno Bela lugosi", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC43", "Digitised": "Y", "Digitised by": "Andrew Paine", "Type": "Live", "Artist": "JBC", "Item Name": "The Butcher Live Onkel Hamburg", "Date": "1985-11-09", "Side A Track List": "Water / Girlfriend / bigfoot motel / kitchen / red pets / human jungle / walk with the devil / marnie / partytime / ASS / Big Saturday / Rain", "Side B Track List": "rain / soul happy hour / death dentist / bus lane / jbvcd / speedy gonzalez / forever / southern mark smith / zombie love / mind like a playgroup / waiting for my man / knocking on heavens door", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC44", "Digitised": "Y", "Digitised by": "Andrew Paine", "Type": "Mixed", "Artist": "", "Item Name": "Radio Fridge Compilation", "Date": "1993", "Side A Track List": "Sir Henry wakes up / Revolution / Beautiful Snow White Hair / The lowliest of metals / Southern Ghost Story / Antartica - Max Mix / Tug Boat Captain / Addiction / Implosion / Murders in the Rue Morgue / Sir Henry and the Hangglider", "Side B Track List": "Funky Donkey  /  Cool Jerk / Juju / mister sun / the impending tour / tabla Jam / Carry me home / Big Eyed beings from venus / Bleak Winter / True Love will find you", "Scanned?": "Yes", "Notes": "A: Viv Stanshall / spacemen 3 / JBC / Peter Blegvad / David J / JBC / Spittle Rattle / Emperors of Ice cream/ viv Stanshall (remixes by the black eg) B: Ahead of reality / The capitols / zapotec / the Verve  / The Black Eg / Ahead of reality / Primal Scre" },
	{ ID: "FMAC45", "Digitised": "Y", "Digitised by": "Andrew Paine", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Festival Dudevenir", "Date": "1993-10-30", "Side A Track List": "", "Side B Track List": "", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC47", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Conspiracy The Loft Ontario", "Date": "?", "Side A Track List": "Saturday / bus lane / southern / kitchen / hard / jungle / dentist / conspiracy", "Side B Track List": "Speedy / devil is my friend", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC48", "Digitised": "Y", "Digitised by": "Nick Bourne", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Group Live at Rockmagasinet Orebro", "Date": "1985-03-22", "Side A Track List": "Marnie / Big foot motel / southern mark smith / soul happy hour / Real men / What's a matter boy/ Only a rumour / Girlfriend / I need meat / playgroup / partytime / bath of bacon / zombie love", "Side B Track List": "Success / Speedy Gonzalez / butch radio Northampton interview nov 84", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC49", "Digitised": "Y", "Digitised by": "?", "Type": "Live", "Artist": "JBC", "Item Name": "Jazz Butcher and Alex Green part 2", "Date": "1987-01-26", "Side A Track List": "Leaving it up to you / vienna / la mer / over the rainbow / roadrunner / skinheads / sweet jane ", "Side B Track List": "water / stand by me || owen and richard 2.23.87 spanish mystery thing / soul happy hour / skinheads / jbCmark thalle 4.17.85", "Scanned?": "Yes", "Notes": "Part two of two   Has spanish mystery thing on it" },
	{ ID: "FMAC50", "Digitised": "Y", "Digitised by": "Robert Rawson", "Type": "", "Artist": "Black EG", "Item Name": "The Black EG Turn Left at the Lights", "Date": "?", "Side A Track List": "The TWilight Zone / British Gas makes it all right / Do ya wanna? / The Good, the bad and the ugly / For painters / Norman Tebbitt's wife's slippers / Jesus RIght now", "Side B Track List": "monster man / Our friends the filth / coney island nightmare / afriacan disease / the Mi-Lai hotel / My radio / so easy (no new york) / Public service broadcast", "Scanned?": "Yes", "Notes": "On the inside cassette card: vote black EG: You buffalo scuzz lowlife apologies for a dried gorilla cum" },
	{ ID: "FMAC51", "Digitised": "Y", "Digitised by": "Robert Rawson", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Group: Live at Stafford CFE", "Date": "1985-05-03", "Side A Track List": "Southern Mark Smith / Bigfoot Motel / real Men / Soul Happy Hour / caroline wheeler / Only a rumour / girlfriend / Girls who keep goldfish / Whats the matter boy / rain / Ineed Meat / Partytime", "Side B Track List": "Pet Semetary / Marnie (encore)", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC52", "Digitised": "Y", "Digitised by": "Ray Hogan", "Type": "Live", "Artist": "JBC", "Item Name": "Jazz Butcher: Loft Berlin", "Date": "1988-03-14", "Side A Track List": "Southern Mark Smith / Real Men / Caroline Wheeler / Out of Touch / Looking for lot 49 / Sex Engine Thing / spooky", "Side B Track List": "Skinheads / GRey Flannelette / Susie / JBVCD / Water / Olof Palme / road runner", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC53", "Digitised": "Y", "Digitised by": "Robert Rawson", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Group Onkel Po Hamburg ", "Date": "1985-04-23", "Side A Track List": "Bath of Bacon / Bigfoot motel / marnie /soul / only a rumour / girlfriend / walk with the devil / caroline wheelers bday / water / chinese envoy / betty page / drink / cowgirl fever ", "Side B Track List": "There's a heartache following me / rain / whats the matter / goldfish / I need meat / real men / my desert / partytime / southern mark smith / zombie love / speedy / playgroup / stephanie says / success", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC54", "Digitised": "Y", "Digitised by": "SIRMick", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Leeds", "Date": "1989-09-01", "Side A Track List": "Big Saturday / Chickentown / New Invention / Mr Odd / Burglar of Love / Hysteria / Bad Dream lover / The Best Way / Zombie Love", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC55", "Digitised": "Y", "Digitised by": "SIRMick", "Type": "Live", "Artist": "JBC", "Item Name": "JBC v CBC Montreal", "Date": "1988-06-10", "Side A Track List": "Saturday / Whitfeld and sarah / sex engine / blame / girl go / grey flannelette / partys over ", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC56", "Digitised": "Y", "Digitised by": "SIRMick", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Edmonton", "Date": "1989-11-25", "Side A Track List": "Where's the a will there's an A / New Invention / chicken town / bicylce kid / burglar / big saturday / angels / dream lover / best way / lot 49 / girl go / southern", "Side B Track List": "Wheeler / JBVPM / mr odd / zombie love / moscow drug club / devil is my friend / partytime / king of joy / betty page / part time punks ", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC57", "Digitised": "Y", "Digitised by": "SIRMick", "Type": "Live", "Artist": "JBC", "Item Name": "Jazz butcher live a the powerhaus london ", "Date": "1989-09-01", "Side A Track List": "Saturday / chickentown / new invention / burglar / bicycle kid / bad dream lover / hysteria / bigfoot", "Side B Track List": "sex engine (end only) / jbvpm / grey flannelette / part time punks", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC58", "Digitised": "Y", "Digitised by": "?", "Type": "", "Artist": "Various", "Item Name": "Downy Mildew and Other Weirdos ", "Date": "? ", "Side A Track List": "Downey mildew: oncoming train / a borrowed chant / trading jewels / elevator / twice told tale / 6 months is along time/ seconds protest / melissa, I know the difference/ sleep / child", "Side B Track List": "The Vaguely familiary; matter of time / bombed / pedby's grace / colour waltz / elwood / LOVE KITTENS:  angels / I don't try", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC59", "Digitised": "Y", "Digitised by": "?", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Milky Way / ICA London", "Date": "July 12 1984 / 12.30.84", "Side A Track List": "Marnie / big foot motel / Real Men / southern Mark Smith / Party time / Leaving it up to you / rain / i need meat / zombie love", "Side B Track List": "Southern Mark Smith / Bigfoot motel / Real Men / Partytime / Girlfriend / Leaving it up to you / girls who keep goldfish / Marnie / I need meat / zombie love / speedy gonzalez", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC60", "Digitised": "Y", "Digitised by": "Dug Douglas", "Type": "", "Artist": "", "Item Name": "Recordings by Pat Fish and Tooolk", "Date": "September 96", "Side A Track List": "?", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "Inside: recordings by Pat fish guitar & tooolk Yamaha pss380 one september afternoon in 1996.  When you've listened to them I hope you'lll agree with your final words: \"That was good\" even more." },
	{ ID: "FMAC62", "Digitised": "Y", "Digitised by": "Dug Douglas", "Type": "", "Artist": "", "Item Name": "Pat Fish Beats", "Date": "", "Side A Track List": "shakey/shame about you/scarlett", "Side B Track List": "", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC46", "Digitised": "AWAITING", "Digitised by": "Dale Jowitt", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Rock Garden London", "Date": "1986-05-03", "Side A Track List": "GRoovin / angels / JBVCD / Human jungle / girlfriend / red pets / whats the matter boy / marnie hard / La mer", "Side B Track List": "Road runner goldsmiths edit second one", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC63", "Digitised": "AWAITING", "Digitised by": "Andy Barding", "Type": "", "Artist": "", "Item Name": "20 wartime greats", "Date": "?", "Side A Track List": "?", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "No notes, only one side labled" },
	{ ID: "FMAC64", "Digitised": "AWAITING", "Digitised by": "Andy Barding", "Type": "Demo", "Artist": "JBC", "Item Name": "Gentleman Demos 2012", "Date": "2012", "Side A Track List": "?", "Side B Track List": "?", "Scanned?": "Yes", "Notes": "No notes, only one side labled" },
	{ ID: "FMAC65", "Digitised": "AWAITING", "Digitised by": "Andy Barding", "Type": "", "Artist": "Black EG", "Item Name": "The Black Eg Mixes August 94", "Date": "August 94", "Side A Track List": "A Tribute to Asian Youth / Mitropa Express / Indianapolis 500 / Long Mixes", "Side B Track List": "Mitropa Express = Long mix / empty Mix / 7 Minute Mix / 5 Minute mix (I don't think so)", "Scanned?": "Yes", "Notes": "Looks like he recorded over a bigstar tape and a JBC recording of Everyone's talkin / President Chang remix / Do you wanna Dance / Over the Rainbow " },
	{ ID: "FMAC66", "Digitised": "AWAITING", "Digitised by": "Andy Barding", "Type": "", "Artist": "Black EG", "Item Name": "The Black Eg", "Date": "1999-06-03", "Side A Track List": "Egpole Warpole ", "Side B Track List": "", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC67", "Digitised": "AWAITING", "Digitised by": "Ruth Tidmarsh", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Tonara Sardinia ", "Date": "1990-08-25", "Side A Track List": "SEx engine / big bad thing / burglar of love / deacon blue / southern mark smith / the basement / she's on drugs / sister death / the best way / lot 49 / girl go / bad dream lover", "Side B Track List": "chicken town / JBVPM / Caroline wheeler / zombie love / huevos / Moscow drug club / soul happy hour / king of joy / ", "Scanned?": "Yes", "Notes": "DEACON BLUE! Huevos Moscow" },
	{ ID: "FMAC68", "Digitised": "AWAITING", "Digitised by": "Ruth Tidmarsh", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Roxy", "Date": "1989-12-09", "Side A Track List": "Big Saturday / Chickentown / Bicycle Kid / New Invention / Angels / Bad Dream Lover / Betway / Lot 49 / Girl Go", "Side B Track List": "Southern Mark Smith / Hysteria / CAroline Wheeler / JB v PM / Mr. Odd / Zombie Love / Betty page / Sex Engine / King of JOy/ Devil is my friend ", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC69", "Digitised": "AWAITING", "Digitised by": "Ruth Tidmarsh", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Paris", "Date": "1993-11-19", "Side A Track List": "Bombed / She's a yo yo / Mr. Odd  / Girl Go / Bakersfield / Sweet Water / Penguins live / Drugs / Skinhead", "Side B Track List": "shirly / Sister death / ghosts / president chang / angels / Road Runner", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC70", "Digitised": "AWAITING", "Digitised by": "Ruth Tidmarsh", "Type": "Live", "Artist": "Sumosonic", "Item Name": "Sumosonic Live Northampton", "Date": "?", "Side A Track List": "Hey Star / Business and Work / God's green earth / Monks of Kung Fu / Radio Saigon / Come Friendly Spaceman", "Side B Track List": "NORTHAMPTOn", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC71", "Digitised": "AWAITING", "Digitised by": "Dug Douglas", "Type": "", "Artist": "", "Item Name": "Subliminal Revolutions", "Date": "?", "Side A Track List": "Subliminal Revolutions Intros etc", "Side B Track List": "Courtesy of Daybreak Soundsystem", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC72", "Digitised": "AWAITING", "Digitised by": "Dale Jowitt", "Type": "Live", "Artist": "JBC", "Item Name": "The Jazz Butcher Markthalle Hamburg ", "Date": "1988-03-17", "Side A Track List": "Southern Mark Smith / Real Men / Carolyn's Wheeler's Birthday Present / Angels / The Best Way / Looking for lot 49 / Sex Engine Thing / OUt of Touch / Grey Flannelette / Susie ", "Side B Track List": "Girlfriend / Spooky / Zombie Love / Olof Palme / Roadrunner / Partytime / JBVCD / Mind like a playgroup / the best way", "Scanned?": "Yes", "Notes": "Back of card, looks like he recorded over another concert." },
	{ ID: "FMAC73", "Digitised": "MAYBE REDO", "Digitised by": "Ray Hogan", "Type": "Live", "Artist": "JBC", "Item Name": "JBC Live in JBC Hamburg / Cesena", "Date": "1985-04-17 / 1986-12-05", "Side A Track List": "zombie Love / Mind like a playgroup / HEroin / bigfoot motel / marnie  || Live in Cesena Vidia dec 5 1986: Forever / The human Jungle / Southern Mark Smith / Partytime", "Side B Track List": "MIX TAPE Paul and linda in the bathroom", "Scanned?": "Yes", "Notes": "" },
	{ ID: "FMAC74", "Digitised": "Y", "Digitised by": "?", "Type": "", "Artist": "Pat + David J", "Item Name": "BBC / Endless Sleep", "Date": "", "Side A Track List": "BBC", "Side B Track List": "Endless Sleep", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC75", "Digitised": "Y", "Digitised by": "Nick Bourne", "Type": "Mixed", "Artist": "Various", "Item Name": "Road Rite", "Date": "", "Side A Track List": "", "Side B Track List": "", "Scanned?": "", "Notes": "" },
	{ ID: "FMAC76", "Digitised": "Y", "Digitised by": "Philip Woodrow", "Type": "", "Artist": "Sumosonic", "Item Name": "Sumo Live – Copy", "Date": "October 97", "Side A Track List": "Monks / God's Green Earth / Business / Sputnik / Dracula / Saigon / Wo'Ful / Spacemen", "Side B Track List": "Copy", "Scanned?": "Yes", "Notes": "" },
];

const FMA_cds = [
{ "ID": "FMACD1", "Item Name": "2018", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD10", "Item Name": "Pat Fish Big Questions _Glowin_ Jingle", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD11", "Item Name": "Sumosonic Backing Tracks", "Digitised by": "", "Type": "", "Artist": "Sumosonic", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD12", "Item Name": "Roger_s Prize", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD13", "Item Name": "The Jazz Butcher - _Mad Ghost_ Demos?", "Digitised by": "", "Type": "", "Artist": "Jazz Butcher", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD14", "Item Name": "Max Eider - Turn Blue", "Digitised by": "", "Type": "", "Artist": "Max Eider", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD15", "Item Name": "Big Planet Summer of 88 Demos", "Digitised by": "", "Type": "Demo", "Artist": "Jazz Butcher", "Date": "1988", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD16", "Item Name": "Stranger Tractor David J Mixes", "Digitised by": "", "Type": "", "Artist": "Stranger Tractors", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD17", "Item Name": "Wilson Original Mixes Jan-03-01", "Digitised by": "", "Type": "", "Artist": "Wilson", "Date": "2001-01-03", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD18", "Item Name": "Wilson Mixes Dec-19-01", "Digitised by": "", "Type": "", "Artist": "Wilson", "Date": "2001-12-19", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD19", "Item Name": "Junkie Christmas", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD1a", "Item Name": "2018", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD2", "Item Name": "Everything", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD2", "Item Name": "_Everything_ False Awakenings EDITED (Remainder  in Progress)", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD20", "Item Name": "Stranger Tractors David J Mixes", "Digitised by": "", "Type": "", "Artist": "Stranger Tractors", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD21", "Item Name": "Love Alastair", "Digitised by": "", "Type": "", "Artist": "", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD3", "Item Name": "Big Return Live LOGO Hamburg Jan-10-2006 2CD", "Digitised by": "", "Type": "Live", "Artist": "Jazz Butcher", "Date": "2006-01-10", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD4", "Item Name": "Live Yoyo Club Shipley UK June-5-2008 (Andrew BrookBanks)", "Digitised by": "", "Type": "Live", "Artist": "Jazz Butcher", "Date": "2008-06-05", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD5", "Item Name": "The Jazz Butcher ~ Terry Warphole - Curious Collaborations", "Digitised by": "", "Type": "", "Artist": "Jazz Butcher", "Date": "", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD6", "Item Name": "Blue Lips In Amsterdam Dec-7-1984", "Digitised by": "", "Type": "Live", "Artist": "Jazz Butcher", "Date": "1984-12-07", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD7", "Item Name": "Only A Rumour April-23-1985 Onkel Po_s", "Digitised by": "", "Type": "Live", "Artist": "Jazz Butcher", "Date": "1985-04-23", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD8", "Item Name": "The Fall Of Jayzilla Feb-8-1985", "Digitised by": "", "Type": "Live", "Artist": "Jazz Butcher", "Date": "1985-02-08", "Tracks": "", "Scanned?": "", "Notes": "" },
{ "ID": "FMACD9", "Item Name": "The Rise Of Felix April-17-1985", "Digitised by": "", "Type": "Live", "Artist": "Jazz Butcher", "Date": "1985-04-17", "Tracks": "", "Scanned?": "", "Notes": "" },
];

const FMA_multis = [
{ "ID": "FMACM01", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "", "Item Name": "The Really Big Multi", "Date": "?", "Tracks": "Our Manc Friends 1 - Jam / Our Manc Friends 2 / Unbearable (spooky dm jam) / Blues for Dead Dean Read / Cute Submarines", "Track Assignments": "?", "Notes": "" },			
{ "ID": "FMACM02", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "", "Item Name": "Plastic Multi", "Date": "August 98", "Tracks": "Plastic Queen 1,2 Back track / The Cartman Song 1,2 Uh..that's it / Deirdre O' Donoghues's Angels", "Track Assignments": "1- 1,2,3 Backtrack fzz gt | 2 - 1,2,3,4 Backtrack, vox Clean Gt | 3 - 1,2 Backgrack Simple / Koan Experiments: 1,2 Random Jam C, 88 BPM", "Notes": "" },			
{ "ID": "FMACM03", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "JBC", "Item Name": "Multi \"Therapist\" 3", "Date": "?", "Tracks": "HoneyWants / Time enough at last / Railway Bridge / Rachel Land ", "Track Assignments": "1 vox 1 guitar 1 feed back 1 fuzz guitar", "Notes": "Looks like backing music for a performance" },			
{ "ID": "FMACM04", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "", "Item Name": "Multi Huevos", "Date": "1905-06-12", "Tracks": "Huevos Rancheros Exhibition a birdland multitrack She's A Yo-Yo + Pascal Tues'", "Track Assignments": "Huevos Back", "Notes": "On the top is marked She's a yo yo and Pascal Tuesday.  Huevos back is written backwards." },			
{ "ID": "FMACM05", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "", "Item Name": "The Lost EG Multi", "Date": "?", "Tracks": "The True Wheel / LA stories (metal mix) / Ecszta / Helium Que? Lucien B / Civil Rights (pascal ansaphone rythem track on ch 2 thru to the end of the tape featuring captain senorita", "Track Assignments": "?", "Notes": "Captain senorita is from a mix tape Tom sent him in the 80s / 90s" },			
{ "ID": "FMACM06", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "Sumosonic", "Item Name": "Sumo Multi", "Date": "?", "Tracks": "?", "Track Assignments": "?", "Notes": "No notes at all." },			
{ "ID": "FMACM07", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "", "Item Name": "Quiet Room Multi", "Date": "", "Tracks": "Alice Cooper - the Quiet Room / Johnny thunders - Diary of a lover / Tom Waits - foreign affair / horrid folksy english pernque / I will survive / bel air / deep dub / mogadon / sexual taboos / la rage / les beatles", "Track Assignments": "?", "Notes": "could be just a mix tape or more." },			
{ "ID": "FMACM08", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "", "Item Name": "Primal Multi", "Date": "1900-03-29", "Tracks": "Dog Nap/  Chill in my heart  - twin peaks / Big motown movie theme / Whaddya? / Slipping Away", "Track Assignments": "?", "Notes": "" },			
{ "ID": "FMACM09", "Digitised": "Y", "Digitised by": "Tim Newman", "Type": "Multitrack Demo", "Artist": "", "Item Name": "Shed Multi", "Date": "?", "Tracks": "I never know when / Anaconda Yawn / Stayin Dirty / Stayin Clean / Je M'en Fous 1 / Je m'en fous 2 / Golf of Death / Code Dvorak", "Track Assignments": "?", "Notes": "most likely 4 track recorded" },			
{ "ID": "FMACM10", "Digitised": "REDO AS MULTI", "Digitised by": "Nick Bourne", "Type": "Multitrack Demo", "Artist": "Black EG", "Item Name": "Mitropa Express Multi", "Date": "?", "Tracks": "", "Track Assignments": "1: Drone 2: Drone 3: Boices 4: radio", "Notes": "Looks like taped over commercial tape for fourtrack" },			
{ "ID": "FMACM12", "Digitised": "AWAITING", "Digitised by": "Robert Rawson", "Type": "Multitrack Demo", "Artist": "Black EG", "Item Name": "Tribute to Asian Youth Gang Multi", "Date": "?", "Tracks": "", "Track Assignments": "Drone / Drone / Czechs / Jungle!", "Notes": "" },			
{ "ID": "FMACM13", "Digitised": "UNASSIGNED", "Digitised by": "", "Type": "Multitrack Demo", "Artist": "", "Item Name": "Cambodia Multi", "Date": "", "Tracks": "", "Track Assignments": "", "Notes": "" },			
{ "ID": "FMACM11", "Digitised": "REDO AS MULTI", "Digitised by": "TravisBickle1963", "Type": "Multitrack Demo", "Artist": "Black EG", "Item Name": "Indianapolis 500 Multi", "Date": "", "Tracks": "Hard Drone / Soft Drone / Brad / Bleeps cars voices", "Track Assignments": "", "Notes": "" },			
];

const FMA_videos = [
{ "ID": "FMAV01", "Source Format": "VHS", "Digitised": "Y", "Digitised by": "Robin Wardell", "Type": "Live", "Artist": "Black EG", "Item Name": "London Footage, No Audio", "Date": "1994-06-01", "Notes": "" },
{ "ID": "FMAV02", "Source Format": "VHS", "Digitised": "Y", "Digitised by": "Robin Wardell", "Type": "", "Artist": "JBC", "Item Name": "Shark Stings, No Audio", "Date": "", "Notes": "soundless live gig projection backdrop video" },
{ "ID": "FMAV03", "Source Format": "VHS", "Digitised": "Y", "Digitised by": "Robin Wardell", "Type": "", "Artist": "Wilson", "Item Name": "Secret Government Promo Video", "Date": "", "Notes": "" },
{ "ID": "FMAV04", "Source Format": "D8", "Digitised": "Y", "Digitised by": "Robin Wardell", "Type": "Live", "Artist": "Wilson", "Item Name": "The Racecourse", "Date": "2004-07-25", "Notes": "" },
{ "ID": "FMAV05", "Source Format": "VHS", "Digitised": "AWAITING", "Digitised by": "Robin Wardell", "Type": "Music Video", "Artist": "JBC", "Item Name": "Sixteen Years", "Date": "", "Notes": "" },
{ "ID": "FMAV06", "Source Format": "VHS", "Digitised": "Y", "Digitised by": "?", "Type": "TV Broadcast", "Artist": "Pat Fish as presenter", "Item Name": "Music Box Transmission", "Date": "1905-06-12", "Notes": "" },
{ "ID": "FMAV07", "Source Format": "VHS", "Digitised": "Y", "Digitised by": "?", "Type": "TV Broadcast", "Artist": "", "Item Name": "Creation TV Spectacular", "Date": "1988-08", "Notes": "" },
{ "ID": "FMAV08", "Source Format": "VHS", "Digitised": "Y", "Digitised by": "?", "Type": "Live TV/Lipsync", "Artist": "JBC", "Item Name": "Shopping Mall of Fear", "Date": "1988-08", "Notes": "" },
];

const FMA_dats = [
{ ID: "FMADAT01", "Digitised": "Y", "Digitised by": "TravisBickle1963", "Type": "Live Backing", "Artist": "Wilson", "Item Name": "Wilson AIR 05", "Date": "", "Track Listing": "", "Scanned?": "Y", "Notes": "" },	
];

const FMAs = {
	cassettes: FMA_cassettes,
	cds: FMA_cds,
	multis: FMA_multis,
	dats: FMA_dats,
	videos: FMA_videos,
};

const useFishyMansionsArchives = (slug: any) => {
	/*
	const fetcher = (url: string) => fetch(url).then((res) => res.json());
	const { data, error, isLoading } = useSWR(`/api/presses`, fetcher);
	return {
		data,
		isLoading,
		error,
	}
	*/
	if (!slug) return {
		isLoading: false,
		data: {
			error: false,
			results: [ FMAs ],
		},
	};
	return {
		isLoading: false,
		data: {
			error: false,
			results: [
				{
					cassette: FMAs.cassettes.find((f: any) => slug ? f?.ID == slug : 1),
					cd: FMAs.cds.find((f: any) => slug ? f?.ID == slug : 1),
					multi: FMAs.multis.find((f: any) => slug ? f?.ID == slug : 1),
					video: FMAs.videos.find((f: any) => slug ? f?.ID == slug : 1),
					dat: FMAs.dats.find((f: any) => slug ? f?.ID == slug : 1),
				}
			]
		}
	}
}

export default useFishyMansionsArchives;
